version: '3.8'

networks:
  mynetwork:
    driver: bridge

volumes:
  db_data:  

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orders_db
    networks:
      - mynetwork
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql  

  webapp:
    image: bogdandanielioan/orders-service:v3
    networks:
      - mynetwork
    ports:
      - "8080:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Server=mysql;Database=orders_db;User=root;Password=root;"
      EUREKA__CLIENT__SHOULDFETCHREGISTRY: false
      EUREKA__CLIENT__SHOULDREGISTERWITHEUREKA: false
    depends_on:
      - mysql
