name: CD - Deploy Express API

on:
  push:
    branches: [ master ]

  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      #      - name: Slack commit message and sha
      #        run: >
      #          curl -X POST -H 'Content-type: application/json'
      #          --data '{"text":":github: ${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }} - ${{ github.event.head_commit.message }}"}'
      #          ${{ secrets.SLACK_WEBHOOK_URL }}

      #      - name: Send Slack Message
      #        run: >
      #          curl -X POST -H 'Content-type: application/json'
      #          --data '{"text":":react: Deployment started :progress_bar: :fingerscrossed:"}'
      #          ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Set build number
        id: build-number
        run: echo "BUILD_NUMBER=$(date '+%d.%m.%Y.%H.%M.%S')" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker Build and push
        run: |
          chmod +x ./.ci/build-publish.sh
          USERNAME=bogdandanielioan \
          REPO=ecommerce-express-api \
          TAG=${{ env.BUILD_NUMBER }} \
          ./.ci/build-publish.sh .

      #      - name: Send Slack Message
      #        run: >
      #          curl -X POST -H 'Content-type: application/json'
      #          --data '{"text":":docker: Image tag:${{ env.BUILD_NUMBER }} pushed to https://hub.docker.com/repository/docker/amigoscode/amigoscode-react"}'
      #          ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Update and commit app version in docker-compose.yml
        run: |
          echo -e "Current ./elasticbeanstalk/docker-compose.yml\n$(cat elasticbeanstalk/docker-compose.yml)"
          sed -i -E 's_(bogdandanielioan/ecommerce-express-api:)([^"]*)_\1'${{ env.BUILD_NUMBER }}'_' elasticbeanstalk/docker-compose.yml
          echo -e "Current elasticbeanstalk/docker-compose.yml\n$(cat elasticbeanstalk/docker-compose.yml)"
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "new app version: ${{ env.BUILD_NUMBER }}"
          git push origin HEAD:master
          # env:
        # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Beanstalk Deploy
        uses: einaregilsson/beanstalk-deploy@ebe3476a4ce991d54336935e75e78dd9d86f9408
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: us-east-1
          environment_name:  server-application
          application_name:  server-application
          deployment_package: ./elasticbeanstalk/docker-compose.yml
          version_label: ${{ env.BUILD_NUMBER }}
          version_description: Version ${{ env.BUILD_NUMBER }} deployed via github actions ${{ github.sha }}
          wait_for_deployment: 120