name: CD - Deploy Express API

on:
  push:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set build number
        id: build-number
        run: echo "BUILD_NUMBER=$(date '+%d.%m.%Y.%H.%M.%S')" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker Build and push
        run: |
          chmod +x online-school-api-master/.ci/build-publish.sh
          USERNAME=bogdandanielioan \
          REPO=test-containers \
          TAG=${{ env.BUILD_NUMBER }} \
          online-school-api-master/.ci/build-publish.sh .

      - name: Update and commit app version in docker-compose.yml
        run: |
          echo -e "Current ./elasticbeanstalk/docker-compose.yml\n$(cat elasticbeanstalk/docker-compose.yml)"
          sed -i -E 's_(bogdandanielioan/school-service:)([^"]*)_\1'${{ env.BUILD_NUMBER }}'_' elasticbeanstalk/docker-compose.yaml
          echo -e "Updated elasticbeanstalk/docker-compose.yaml\n$(cat elasticbeanstalk/docker-compose.yaml)"
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "new app version: ${{ env.BUILD_NUMBER }}"
          git push origin HEAD:master
